# Generated by Django 5.0.7 on 2025-07-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
