# Generated by Django 5.0.7 on 2025-07-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_student_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
    ]
