# Generated by Django 5.0.7 on 2025-07-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_student_batch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_per_student_per_date',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
