# Generated by Django 5.0.7 on 2025-07-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_changerequest_changerequestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
