# Generated by Django 5.0.7 on 2025-07-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_father_student_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls')], default='boys', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
