# Generated by Django 5.0.7 on 2025-07-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_student_gender_alter_student_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_tests', to='api.class')),
            ],
            options={
                'unique_together': {('title', 'class_fk', 'month')},
            },
        ),
        migrations.CreateModel(
            name='TestMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_marks', to='api.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_marks', to='api.monthlytest')),
            ],
            options={
                'unique_together': {('test', 'student')},
            },
        ),
    ]
