# Generated by Django 5.0.7 on 2025-07-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_monthlytest_testmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlytest',
            name='date',
        ),
    ]
