# Generated by Django 5.0.7 on 2025-07-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_monthlytest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='model_type',
            field=models.CharField(choices=[('marks', 'Marks'), ('attendance', 'Attendance'), ('student', 'Student'), ('fee', 'Fee'), ('monthly_test', 'Monthly Test'), ('test_marks', 'Test Marks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
