# Generated by Django 5.0.7 on 2025-07-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_emailaccess_pendingregistration_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingregistration',
            options={'verbose_name': 'Email Address', 'verbose_name_plural': 'Email Addresses'},
        ),
        migrations.AddField(
            model_name='emailaccess',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('staff', 'Staff'), ('vice_principal', 'Vice Principal')], default='teacher', max_length=20),
        ),
    ]
