# Generated by Django 5.0.7 on 2025-07-06 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_pendingregistration_options_emailaccess_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccess',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='teacher_accesses', to='api.class'),
        ),
        migrations.AlterField(
            model_name='emailaccess',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_accesses', to='api.class'),
        ),
    ]
