# Generated by Django 5.0.7 on 2025-08-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_emailaccess_assigned_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
