# Generated by Django 5.0.7 on 2025-08-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_is_archived_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
